# MNIST hand written digit classification 

We tackle the classical MNIST digit classification problem using various neural networks.  

The data is of shape 28x28x1, where each data represents a picture of a handwritten digit from 0-9. Our task is to classify which digit it is.  

The first network I will try is a simple fully connected layer. The setup is Paperspace Gradient NVIDIA P-4000 GPU. 

In [3]:
pip install pandas 

     |████████████████████████████████| 10.0MB 13.5MB/s eta 0:00:01
     |████████████████████████████████| 512kB 56.6MB/s eta 0:00:01
You should consider upgrading via the 'pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


### Simple Dense Model 

In [70]:
train = pd.read_csv("train.csv")
X_test = pd.read_csv("test.csv")
Y_train = train["label"]
X_train = train.drop(labels = ["label"],axis = 1)  

In [71]:
X_train = np.asarray(X_train) 
Y_train = np.asarray(Y_train) 

In [72]:
X_train = X_train / 255.0

In [73]:
from tensorflow.keras.utils import to_categorical 
#Y_train = to_categorical(Y_train)   

print(X_train.shape)
print(Y_train.shape)

(42000, 784)
(42000,)


In [74]:
def FCN(): 
    model = models.Sequential()
    model.add(layers.Dense(512, activation = 'relu', input_shape=(28*28,)))
    model.add(layers.Dense(10, activation = 'softmax'))
    model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
    return model 
    

In [75]:
model = FCN() 
model.fit(X_train, Y_train, epochs = 10, batch_size = 128)

Train on 42000 samples
Epoch 1/10
42000/42000 [==============================] - 1s 27us/sample - loss: 0.3052 - accuracy: 0.9134
Epoch 2/10
42000/42000 [==============================] - 1s 20us/sample - loss: 0.1286 - accuracy: 0.9622
Epoch 3/10
42000/42000 [==============================] - 1s 20us/sample - loss: 0.0842 - accuracy: 0.9760
Epoch 4/10
42000/42000 [==============================] - 1s 20us/sample - loss: 0.0590 - accuracy: 0.9831
Epoch 5/10
42000/42000 [==============================] - 1s 20us/sample - loss: 0.0448 - accuracy: 0.9874
Epoch 6/10
42000/42000 [==============================] - 1s 20us/sample - loss: 0.0318 - accuracy: 0.9913
Epoch 7/10
42000/42000 [==============================] - 1s 20us/sample - loss: 0.0258 - accuracy: 0.9931
Epoch 8/10
42000/42000 [==============================] - 1s 20us/sample - loss: 0.0180 - accuracy: 0.9958
Epoch 9/10
42000/42000 [==============================] - 1s 21us/sample - loss: 0.0134 - accuracy: 0.9972
Epoch 10/10
42

In [77]:
X_test = np.asarray(X_test) 
X_test = X_test/255.0 

In [79]:
predicted = model.predict_classes(X_test)
predicted

array([2, 0, 9, ..., 3, 9, 2])

In [82]:
submission = pd.read_csv('sample_submission.csv')
submission['Label'] = predicted 
submission.head(10)

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      9
4        5      3
5        6      7
6        7      0
7        8      3
8        9      0
9       10      3

In [83]:
submission.to_csv("FCN.csv",index=False) 

Upon submitting our prediction from the dense network, we get an accuracy score of 97.57% on the public leaderboard. 

### Simple CNN Architecture 

This time, I will try to construct a simple CNN architecture with a few Conv2D and MaxPooling2D layers 

In [84]:
def custom_CNN(): 
    model = models.Sequential()
    model.add(layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
    model.add(layers.MaxPooling2D((2,2))) 
    model.add(layers.Conv2D(64,(3,3),activation='relu'))
    model.add(layers.MaxPooling2D(2,2)) 
    model.add(layers.Conv2D(64,(3,3),activation='relu'))
    model.add(layers.Flatten()) 
    model.add(layers.Dense(64,activation='relu'))
    model.add(layers.Dense(10,activation='softmax')) 
    model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
    return model 

In [87]:
train = pd.read_csv("train.csv")
X_test = pd.read_csv("test.csv")
Y_train = train["label"]
X_train = train.drop(labels = ["label"],axis = 1)  

X_train = np.asarray(X_train) 
X_train = X_train.reshape((-1,28,28,1)) 
X_train = X_train/255.0 
Y_train = np.asarray(Y_train)    

print(X_train.shape) 
print(Y_train.shape)

X_test = np.asarray(X_test) 
X_test = X_test.reshape((-1,28,28,1)) 
X_test = X_test/255.0 

(42000, 28, 28, 1)
(42000,)


In [88]:
model = custom_CNN() 
model.fit(X_train, Y_train, epochs = 10, batch_size = 128)

Train on 42000 samples
Epoch 1/10
42000/42000 [==============================] - 4s 99us/sample - loss: 0.3099 - accuracy: 0.9057
Epoch 2/10
42000/42000 [==============================] - 2s 38us/sample - loss: 0.0738 - accuracy: 0.9772
Epoch 3/10
42000/42000 [==============================] - 2s 38us/sample - loss: 0.0494 - accuracy: 0.9847
Epoch 4/10
42000/42000 [==============================] - 2s 40us/sample - loss: 0.0391 - accuracy: 0.9874
Epoch 5/10
42000/42000 [==============================] - 2s 39us/sample - loss: 0.0322 - accuracy: 0.9890
Epoch 6/10
42000/42000 [==============================] - 2s 38us/sample - loss: 0.0252 - accuracy: 0.9917
Epoch 7/10
42000/42000 [==============================] - 2s 39us/sample - loss: 0.0210 - accuracy: 0.9933
Epoch 8/10
42000/42000 [==============================] - 2s 38us/sample - loss: 0.0164 - accuracy: 0.9949
Epoch 9/10
42000/42000 [==============================] - 2s 38us/sample - loss: 0.0166 - accuracy: 0.9945
Epoch 10/10
42

In [89]:
predicted = model.predict_classes(X_test)
predicted

array([2, 0, 9, ..., 3, 9, 2])

In [90]:
submission = pd.read_csv('sample_submission.csv')
submission['Label'] = predicted 
submission.head(10)

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      0
4        5      3
5        6      7
6        7      0
7        8      3
8        9      0
9       10      3

In [92]:
submission.to_csv('simple_CNN.csv',index=False)

Upon submission, we get an accuracy of 99.06% on the public leaderboard. This is an improvement from the simple dense network. 

### Conclusion

From this small experiment, we could see the power of convolution neueral networks on image classifcation problems. 

Other things we could do to improve performance on the MNIST dataset 
1. Try augmenting data using ImageDataGenerator (like rotating handwritten digits)

2. Try pretrained models such as LeNet, VGG-16, etc.

3. For simplicity, I have not used validation data during training to tune the model. Rather, I have directly used the provided test data to make predictions on the trained model. For better analysis, it is always best to split the full train data to train and validation set, and then run for many epochs (with various values of hyperparameters) to decide on which epoch to stop and which hyperparameter is the best. Once these values are decided, we train the model on the full dataset with the hyperparameters we have found to be the best. Then we make our prediction. 

### Follow Up 

Let us try to augment data using ImageDataGenerator. After augmenting the data, we will trty to submit on Kaggle to see its performance

In [44]:
import pandas as pd 
import numpy as np 
import tensorflow.keras 
from tensorflow.keras.utils import to_categorical


train = pd.read_csv("train.csv")
X_test = pd.read_csv("test.csv")
Y_train = train["label"]
X_train = train.drop(labels = ["label"],axis = 1)  
X_train = np.asarray(X_train) 
X_train = X_train.reshape((-1,28,28,1)) 
X_train = X_train / 255.0
Y_train = np.asarray(Y_train) 
Y_train = to_categorical(Y_train)


In [45]:
from tensorflow.keras import models, layers 
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Input, Dense, Flatten,Activation,AveragePooling2D,BatchNormalization
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.image import ImageDataGenerator

''' a simple version of CNN we used above '''
def custom_CNN(): 
    model = models.Sequential()
    model.add(layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))
    model.add(layers.MaxPooling2D((2,2))) 
    model.add(layers.Conv2D(64,(3,3),activation='relu'))
    model.add(layers.MaxPooling2D(2,2)) 
    model.add(layers.Conv2D(64,(3,3),activation='relu'))
    model.add(layers.Flatten()) 
    model.add(layers.Dense(64,activation='relu'))
    model.add(layers.Dense(10,activation='softmax')) 
    model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
    return model 


''' improved CNN '''
def improved_CNN(): 
    model = Sequential()
    model.add(Conv2D(filters=64, kernel_size = (3,3), activation="relu", input_shape=(28,28,1)))
    model.add(Conv2D(filters=64, kernel_size = (3,3), activation="relu"))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(BatchNormalization())
    model.add(Conv2D(filters=128, kernel_size = (3,3), activation="relu"))
    model.add(Conv2D(filters=128, kernel_size = (3,3), activation="relu"))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(BatchNormalization())    
    model.add(Conv2D(filters=256, kernel_size = (3,3), activation="relu"))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Flatten())
    model.add(BatchNormalization())
    model.add(Dense(512,activation="relu"))
    model.add(Dense(10,activation="softmax"))
    model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
    return model 

    

In [46]:
'''create ImageDataGenerator. The chosen hyperparameters are arbitrary''' 

datagen = ImageDataGenerator(
        rotation_range=10,  
        zoom_range = 0.10,  
        width_shift_range=0.1, 
        height_shift_range=0.1)
train_gen = datagen.flow(X_train, Y_train, batch_size=64) 


In [ ]:
model = improved_CNN()
model.fit_generator(train_gen,epochs=50,verbose=1)

Epoch 1/50
657/657 [==============================] - 40s 61ms/step - loss: 0.1508 - accuracy: 0.9523
Epoch 2/50
657/657 [==============================] - 40s 61ms/step - loss: 0.0656 - accuracy: 0.9805
Epoch 3/50
657/657 [==============================] - 40s 61ms/step - loss: 0.0523 - accuracy: 0.9845
Epoch 4/50
657/657 [==============================] - 40s 61ms/step - loss: 0.0485 - accuracy: 0.9853
Epoch 5/50
657/657 [==============================] - 40s 61ms/step - loss: 0.0451 - accuracy: 0.9860
Epoch 6/50
657/657 [==============================] - 40s 62ms/step - loss: 0.0386 - accuracy: 0.9885
Epoch 7/50
657/657 [==============================] - 40s 61ms/step - loss: 0.0337 - accuracy: 0.9894
Epoch 8/50
657/657 [==============================] - 40s 61ms/step - loss: 0.0351 - accuracy: 0.9895
Epoch 9/50
657/657 [==============================] - 40s 60ms/step - loss: 0.0317 - accuracy: 0.9902
Epoch 10/50
657/657 [==============================] - 40s 61ms/step - loss: 0.029

In [29]:
X_test = np.asarray(X_test) 
X_test = X_test.reshape((-1,28,28,1)) 
X_test = X_test/255.0 

predicted = model.predict_classes(X_test)
predicted

array([2, 0, 9, ..., 3, 9, 2])

In [30]:
submission = pd.read_csv('sample_submission.csv')
submission['Label'] = predicted 
submission.head(10) 

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      0
4        5      3
5        6      7
6        7      0
7        8      3
8        9      0
9       10      3

In [31]:
submission.to_csv('augmented_improved_CNN.csv',index=False) 

The submission resulted in a score of 99.37% accuracy on the public leaderboard. Definitely an improvement compared to our previous submission! 